/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_boomaa_opends_usb_PlaceholderWindow */

#ifndef _Included_com_boomaa_opends_usb_PlaceholderWindow
#define _Included_com_boomaa_opends_usb_PlaceholderWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_boomaa_opends_usb_PlaceholderWindow
 * Method:    createWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_boomaa_opends_usb_PlaceholderWindow_createWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_boomaa_opends_usb_PlaceholderWindow
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_boomaa_opends_usb_PlaceholderWindow_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
