/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_boomaa_opends_usb_DirectInputDevice */

#ifndef _Included_com_boomaa_opends_usb_DirectInputDevice
#define _Included_com_boomaa_opends_usb_DirectInputDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    enumObjects
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_enumObjects
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    poll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_poll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    acquire
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_acquire
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    unacquire
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_unacquire
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    fetchDeviceState
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_fetchDeviceState
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    setDataFormat
 * Signature: (JI[Lcom/boomaa/opends/usb/DIDeviceObject;)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_setDataFormat
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    setCooperativeLevel
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_setCooperativeLevel
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    fetchRangeProperty
 * Signature: (JI[J)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_fetchRangeProperty
  (JNIEnv *, jclass, jlong, jint, jlongArray);

/*
 * Class:     com_boomaa_opends_usb_DirectInputDevice
 * Method:    fetchDeadbandProperty
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_usb_DirectInputDevice_fetchDeadbandProperty
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
