/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_boomaa_opends_usb_DirectInput */

#ifndef _Included_com_boomaa_opends_usb_DirectInput
#define _Included_com_boomaa_opends_usb_DirectInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_boomaa_opends_usb_DirectInput
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_boomaa_opends_usb_DirectInput_create
  (JNIEnv *, jobject);

/*
 * Class:     com_boomaa_opends_usb_DirectInput
 * Method:    enumDevices
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_boomaa_opends_usb_DirectInput_enumDevices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_boomaa_opends_usb_DirectInput
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_boomaa_opends_usb_DirectInput_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
