/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_boomaa_opends_util_battery_Win32BatteryJNI */

#ifndef _Included_com_boomaa_opends_util_battery_Win32BatteryJNI
#define _Included_com_boomaa_opends_util_battery_Win32BatteryJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_boomaa_opends_util_battery_Win32BatteryJNI
 * Method:    isAC
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_boomaa_opends_util_battery_Win32BatteryJNI_isAC
  (JNIEnv *, jclass);

/*
 * Class:     com_boomaa_opends_util_battery_Win32BatteryJNI
 * Method:    getFlag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_util_battery_Win32BatteryJNI_getFlag
  (JNIEnv *, jclass);

/*
 * Class:     com_boomaa_opends_util_battery_Win32BatteryJNI
 * Method:    getPercent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_util_battery_Win32BatteryJNI_getPercent
  (JNIEnv *, jclass);

/*
 * Class:     com_boomaa_opends_util_battery_Win32BatteryJNI
 * Method:    getLifeTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_util_battery_Win32BatteryJNI_getLifeTime
  (JNIEnv *, jclass);

/*
 * Class:     com_boomaa_opends_util_battery_Win32BatteryJNI
 * Method:    getFullTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_boomaa_opends_util_battery_Win32BatteryJNI_getFullTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif